import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/41r7mT0FfPL._SX324_BO1,204,203,200_.jpg",
    title: "The Humans",
    author: "Matt Haig",
    price: 342,
    categoryName: "fiction",
    rating: 4.5,
    pages: 320,
    delivery: 3,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/51sNstCfaEL._SX311_BO1,204,203,200_.jpg",
    title: "White Clouds, Green Mountains ",
    author: "Ruskin Bond",
    price: 183,
    categoryName: "fiction",
    rating: 4.5,
    pages: 132,
    delivery: 3,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/41e+TR4xPDL._SX328_BO1,204,203,200_.jpg",
    title: "The Alchemist ",
    author: " Paulo Coelho",
    price: 237,
    categoryName: "fiction",
    rating: 3,
    pages: 172,
    delivery: 3,
  },
  {
    _id: uuid(),
    title: "The Theory Of Everything ",
    img: "https://m.media-amazon.com/images/I/51oHUvYzbsL._SX327_BO1,204,203,200_.jpg",
    author: "Stephen Hawking",
    price: 500,
    categoryName: "non-fiction",
    pages: 140,
    rating: 3.5,
    delivery: 3,
  },
  {
    _id: uuid(),
    title: "Man's Search For Meaning",
    img: "https://m.media-amazon.com/images/I/41ZgK6u73qL._SX313_BO1,204,203,200_.jpg",
    author: "Viktor E. Frankl",
    price: 600,
    categoryName: "non-fiction",
    rating: 5,
    pages: 160,
    delivery: 3,
  },
  {
    _id: uuid(),
    title: "The Almanack Of Naval Ravikant",
    img: "https://m.media-amazon.com/images/I/31bDtgec8NL._SX324_BO1,204,203,200_.jpg",
    author: "Eric Jorgenson",
    price: 600,
    categoryName: "non-fiction",
    rating: 4,
    pages: 242,
    delivery: 3,
  },
  {
    _id: uuid(),
    title: "The Ultimate Hitchhiker's Guide to the Galaxy",
    img: "https://m.media-amazon.com/images/I/51x53xtKI0L._SX325_BO1,204,203,200_.jpg",
    author: " Douglas Adams ",
    price: 500,
    categoryName: "fiction",
    rating: 4.1,
    pages: 832,
    delivery: 3,
  },
  {
    _id: uuid(),
    title: "Atomic Habits",
    img: "https://m.media-amazon.com/images/I/51-nXsSRfZL._SX328_BO1,204,203,200_.jpg",
    author: "James Clea",
    price: 700,
    categoryName: "self-help",
    rating: 4,
    pages: 320,
    delivery: 3,
  },
  {
    _id: uuid(),
    title: "Ikigai",
    img: "https://m.media-amazon.com/images/I/51xwGSNX-EL._SX356_BO1,204,203,200_.jpg",
    author: "Francesc Miralles",
    price: 1000,
    categoryName: "self-help",
    rating: 5,
    pages: 320,
    delivery: 3,
  },
  {
    _id: uuid(),
    title: "THE HEADSPACE GUIDE TO MEDITATION & MINDFULNESS",
    img: "https://m.media-amazon.com/images/I/41M4el8UKvL._SX324_BO1,204,203,200_.jpg",
    author: "Andy Puddicombe",
    price: 1000,
    categoryName: "self-help",
    rating: 5,
    pages: 320,
    delivery: 3,
  },
];
